<?php

use App\Http\Controllers\PostController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\InteractionController;
use App\Http\Controllers\PeopleController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\ChatController;
use App\Http\Controllers\SecurityController;
use App\Http\Controllers\ProfileInteractionController;
use App\Http\Controllers\FriendController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\StoryController;
use Illuminate\Support\Facades\Route;

Route::get('/', [PostController::class, 'index']);
Route::get('/posts', [PostController::class, 'index'])->name('posts.index');
Route::get('/share/{token}', [PostController::class, 'shared'])->name('posts.shared');
Route::get('/people', [PeopleController::class, 'index'])->name('people.index');
Route::get('/people/{user}', [PeopleController::class, 'show'])->name('people.show');
Route::middleware('auth')->group(function (): void {
	Route::get('/stories/create', [StoryController::class, 'create'])->name('stories.create');
	Route::post('/stories', [StoryController::class, 'store'])->name('stories.store');
	Route::post('/stories/{story}/reply', [StoryController::class, 'reply'])->name('stories.reply');
	Route::post('/stories/{story}/react/{type}', [StoryController::class, 'react'])->name('stories.react');
	Route::post('/stories/{story}/share', [StoryController::class, 'share'])->name('stories.share');
	Route::post('/stories/{story}/mute', [StoryController::class, 'mute'])->name('stories.mute');
	Route::post('/stories/{story}/report', [StoryController::class, 'report'])->name('stories.report');
	Route::get('/friends', [FriendController::class, 'index'])->name('friends.index');
	Route::get('/stories/create', [StoryController::class, 'create'])->name('stories.create');
	Route::get('/stories/{story}', [StoryController::class, 'show'])->name('stories.show');
	Route::get('/notifications', [NotificationController::class, 'index'])->name('notifications.index');
	Route::get('/notifications/{notification}/read', [NotificationController::class, 'read'])->name('notifications.read');
	Route::post('/notifications/read-all', [NotificationController::class, 'readAll'])->name('notifications.read-all');
	Route::post('/people/{user}/friend', [FriendController::class, 'send'])->name('friends.send');
	Route::post('/people/{user}/friend/toggle', [FriendController::class, 'send'])->name('people.friend');
	Route::post('/friendships/{friendship}/accept', [FriendController::class, 'accept'])->name('friends.accept');
	Route::post('/friendships/{friendship}/reject', [FriendController::class, 'reject'])->name('friends.reject');
	Route::post('/friendships/{friendship}/cancel', [FriendController::class, 'cancel'])->name('friends.cancel');
	Route::delete('/people/{user}/friend', [FriendController::class, 'remove'])->name('friends.remove');
	Route::post('/people/{user}/follow', [ProfileInteractionController::class, 'follow'])->name('people.follow');
	Route::post('/people/{user}/block', [ProfileInteractionController::class, 'block'])->name('people.block');
	Route::post('/people/{user}/report', [ProfileInteractionController::class, 'report'])->name('people.report');
	Route::post('/people/{user}/share', [ProfileInteractionController::class, 'share'])->name('people.share');
});
Route::middleware('auth')->group(function (): void {
	Route::get('/messages', [ChatController::class, 'index'])->name('chat.index');
	Route::post('/messages/groups', [ChatController::class, 'createGroup'])->name('chat.groups.store');
	Route::get('/messages/with/{user}', [ChatController::class, 'with'])->name('chat.with');
	Route::get('/messages/{conversation}/older', [ChatController::class, 'older'])->name('chat.older');
	Route::get('/messages/{conversation}', [ChatController::class, 'show'])->name('chat.show');
	Route::post('/messages/{conversation}', [ChatController::class, 'send'])->name('chat.send');
	Route::post('/messages/{message}/react/{type}', [ChatController::class, 'react'])->name('chat.message.react');
	Route::put('/message/{message}', [ChatController::class, 'updateMessage'])->name('chat.message.update');
	Route::delete('/message/{message}', [ChatController::class, 'deleteMessage'])->name('chat.message.delete');
	Route::post('/message/{message}/pin', [ChatController::class, 'pinMessage'])->name('chat.message.pin');
});
Route::get('/login', [AuthController::class, 'createLogin'])->middleware('guest')->name('login');
Route::post('/login', [AuthController::class, 'login'])->name('login.store');
Route::get('/register', [AuthController::class, 'createRegister'])->middleware('guest')->name('register');
Route::post('/register', [AuthController::class, 'register'])->name('register.store');
Route::post('/logout', [AuthController::class, 'logout'])->middleware('auth')->name('logout');
Route::post('/account/reactivate', [SecurityController::class, 'reactivate'])->middleware('throttle:6,1')->name('account.reactivate');
Route::get('/account/reactivate', fn () => view('auth.reactivate'))->middleware('guest')->name('account.reactivate.form');
Route::get('/email/verify', fn () => view('auth.verify-email'))->middleware('auth')->name('verification.notice');
Route::get('/email/verify/{user}/{hash}', [AuthController::class, 'verify'])->middleware(['auth', 'signed', 'throttle:6,1'])->name('verification.verify');
Route::post('/email/verification-notification', [AuthController::class, 'resendVerification'])->middleware(['auth', 'throttle:6,1'])->name('verification.send');
Route::get('/forgot-password', [AuthController::class, 'forgotPassword'])->middleware('guest')->name('password.request');
Route::post('/forgot-password', [AuthController::class, 'sendResetLink'])->middleware(['guest', 'throttle:6,1'])->name('password.email');
Route::get('/reset-password/{token}', [AuthController::class, 'resetPassword'])->middleware('guest')->name('password.reset');
Route::post('/reset-password', [AuthController::class, 'updatePassword'])->middleware('guest')->name('password.update');
Route::get('/two-factor/challenge', [SecurityController::class, 'challenge'])->name('two-factor.challenge');
Route::post('/two-factor/challenge', [SecurityController::class, 'verifyChallenge'])->middleware('throttle:6,1')->name('two-factor.verify');
Route::get('/dashboard', DashboardController::class)->middleware('auth')->name('dashboard');
Route::middleware('auth')->group(function (): void {
	Route::get('/account/security', [SecurityController::class, 'index'])->name('account.security');
	Route::put('/account/preferences', [SecurityController::class, 'preferences'])->name('account.preferences');
	Route::delete('/account/devices/{device}', [SecurityController::class, 'revokeDevice'])->name('account.devices.revoke');
	Route::post('/account/devices/revoke-all', [SecurityController::class, 'revokeAllDevices'])->name('account.devices.revoke-all');
	Route::get('/account/two-factor', [SecurityController::class, 'showTwoFactor'])->name('two-factor.setup');
	Route::post('/account/two-factor', [SecurityController::class, 'beginTwoFactor'])->name('two-factor.begin');
	Route::put('/account/two-factor', [SecurityController::class, 'confirmTwoFactor'])->name('two-factor.confirm');
	Route::delete('/account/two-factor', [SecurityController::class, 'disableTwoFactor'])->name('two-factor.disable');
	Route::post('/account/deactivate', [SecurityController::class, 'deactivate'])->name('account.deactivate');
	Route::delete('/account', [SecurityController::class, 'delete'])->name('account.delete');
	Route::get('/posts/create', [PostController::class, 'create'])->name('posts.create');
	Route::post('/posts', [PostController::class, 'store'])->name('posts.store');
	Route::get('/posts/{post}/edit', [PostController::class, 'edit'])->name('posts.edit');
	Route::put('/posts/{post}', [PostController::class, 'update'])->name('posts.update');
	Route::delete('/posts/{post}', [PostController::class, 'destroy'])->name('posts.destroy');
	Route::post('/posts/{post}/comments', [InteractionController::class, 'comment'])->name('posts.comments');
	Route::post('/posts/{post}/like', [InteractionController::class, 'like'])->name('posts.like');
	Route::post('/posts/{post}/reaction/{type}', [InteractionController::class, 'reaction'])->name('posts.reaction');
	Route::post('/posts/{post}/share', [InteractionController::class, 'share'])->name('posts.share');
	Route::get('/profile/edit', [ProfileController::class, 'edit'])->name('profile.edit');
	Route::put('/profile', [ProfileController::class, 'update'])->name('profile.update');
});
Route::get('/posts/{post}', [PostController::class, 'show'])->name('posts.show');

