@extends('layouts.app', ['title' => 'Edit profile'])

@section('content')
<div class="form-wrap profile-form"><a class="back-link" href="{{ route('people.show', $user) }}">← Back to profile</a><p class="eyebrow">Your identity</p><h1>Make your profile yours.</h1><p class="lede">Help people know who they are connecting with.</p>
<form class="post-form" method="POST" action="{{ route('profile.update') }}" enctype="multipart/form-data">@csrf @method('PUT')
    @if ($errors->any())<div class="flash flash-error">Please check the highlighted fields and try again.</div>@endif
    <div class="profile-photo-field"><img src="{{ $user->profile_photo_url }}" alt=""><div><label for="profile_photo">Profile photo</label><input id="profile_photo" name="profile_photo" type="file" accept="image/jpeg,image/png,image/webp"><span class="field-hint">JPEG, PNG, or WebP. Maximum 20 MB.</span>@error('profile_photo')<span class="field-error">{{ $message }}</span>@enderror</div></div>
    <div class="cover-upload-field"><label for="cover_photo">Cover photo</label><div class="cover-preview" style="@if ($user->cover_photo) background-image:url('{{ asset('storage/'.$user->cover_photo) }}') @endif"></div><input id="cover_photo" name="cover_photo" type="file" accept="image/jpeg,image/png,image/webp"><span class="field-hint">A wide photo for the top of your profile. Maximum 20 MB.</span>@error('cover_photo')<span class="field-error">{{ $message }}</span>@enderror</div>
    <div class="field"><label for="name">Name</label><input id="name" name="name" value="{{ old('name', $user->name) }}" required>@error('name')<span class="field-error">{{ $message }}</span>@enderror</div>
    <div class="field"><label for="email">Email</label><input id="email" name="email" type="email" value="{{ old('email', $user->email) }}" required><span class="field-hint">You use this email to log in.</span>@error('email')<span class="field-error">{{ $message }}</span>@enderror</div>
    <div class="field"><label for="username">Username</label><input id="username" name="username" value="{{ old('username', $profile->username) }}" required><span class="field-hint">Letters, numbers, dashes, and underscores.</span>@error('username')<span class="field-error">{{ $message }}</span>@enderror</div>
    <div class="field"><label for="bio">Bio</label><textarea id="bio" name="bio" rows="4" maxlength="1000" placeholder="A few words about you...">{{ old('bio', $user->bio) }}</textarea></div>
    <div class="form-row"><div class="field"><label for="gender">Gender</label><input id="gender" name="gender" value="{{ old('gender', $profile->gender) }}"></div><div class="field"><label for="birthday">Birthday</label><input id="birthday" name="birthday" type="date" value="{{ old('birthday', optional($profile->birthday)->format('Y-m-d')) }}"></div></div>
    <div class="form-row"><div class="field"><label for="profession">Profession</label><input id="profession" name="profession" value="{{ old('profession', $user->profession) }}" placeholder="Designer, teacher, developer..."></div><div class="field"><label for="location">Location</label><input id="location" name="location" value="{{ old('location', $user->location) }}" placeholder="City, country"></div></div>
    <div class="form-row"><div class="field"><label for="workplace">Workplace</label><input id="workplace" name="workplace" value="{{ old('workplace') }}"></div><div class="field"><label for="education">Education</label><input id="education" name="education" value="{{ old('education') }}"></div></div>
    <div class="form-row"><div class="field"><label for="relationship_status">Relationship status</label><input id="relationship_status" name="relationship_status" value="{{ old('relationship_status', $profile->relationship_status) }}"></div><div class="field"><label for="website">Website</label><input id="website" name="website" type="url" value="{{ old('website', $profile->website) }}"></div></div>
    <div class="form-row"><div class="field"><label for="contact_email">Contact email</label><input id="contact_email" name="contact_email" type="email" value="{{ old('contact_email', $profile->contact_email) }}"></div><div class="field"><label for="contact_phone">Contact phone</label><input id="contact_phone" name="contact_phone" type="tel" value="{{ old('contact_phone', $profile->contact_phone) }}"></div></div>
    <fieldset class="security-section"><legend>Public profile</legend><p class="field-hint">Choose which details visitors can see.</p>@foreach(['bio' => 'Bio', 'gender' => 'Gender', 'birthday' => 'Birthday', 'location' => 'Location', 'workplace' => 'Workplace', 'education' => 'Education', 'relationship_status' => 'Relationship status', 'contact' => 'Contact information', 'website' => 'Website'] as $field => $label)<label class="check"><input type="checkbox" name="public_fields[]" value="{{ $field }}" @checked(($profile->visibility[$field] ?? true))>{{ $label }}</label>@endforeach</fieldset>
    <div class="form-row"><div class="field"><label for="interests">Interests</label><input id="interests" name="interests" value="{{ old('interests', $user->interests) }}" placeholder="Design, music, travel"></div><div class="field"><label for="hobbies">Hobbies</label><input id="hobbies" name="hobbies" value="{{ old('hobbies', $user->hobbies) }}" placeholder="Cooking, hiking, books"></div></div>
    <div class="security-section">
        <h2>Update password</h2>
        <p class="field-hint">Leave these fields empty to keep your current password.</p>
        <div class="field"><label for="current_password">Current password</label><input id="current_password" name="current_password" type="password" autocomplete="current-password">@error('current_password')<span class="field-error">{{ $message }}</span>@enderror</div>
        <div class="form-row"><div class="field"><label for="password">New password</label><input id="password" name="password" type="password" autocomplete="new-password">@error('password')<span class="field-error">{{ $message }}</span>@enderror</div><div class="field"><label for="password_confirmation">Confirm new password</label><input id="password_confirmation" name="password_confirmation" type="password" autocomplete="new-password"></div></div>
    </div>
    <div class="form-actions"><button class="button button-dark" type="submit">Save profile</button><a class="button button-quiet" href="{{ route('people.show', $user) }}">Cancel</a></div>
</form></div>
@endsection