@extends('layouts.app', ['title' => 'Account security'])
@section('content')
<div class="form-wrap"><p class="eyebrow">Account settings</p><h1>Keep your account in your hands.</h1>
<form class="post-form" method="POST" action="{{ route('account.preferences') }}">@csrf @method('PUT')
<div class="form-row"><div class="field"><label for="locale">Language</label><select id="locale" name="locale"><option value="en" @selected($user->locale === 'en')>English</option></select></div><div class="field"><label for="timezone">Time zone</label><select id="timezone" name="timezone">@foreach(timezone_identifiers_list() as $timezone)<option value="{{ $timezone }}" @selected($user->timezone === $timezone)>{{ $timezone }}</option>@endforeach</select></div></div><button class="button button-dark" type="submit">Save preferences</button></form>
<section class="security-section"><h2>Two-factor authentication</h2><p class="field-hint">{{ $user->two_factor_enabled ? 'Enabled. Your account asks for a code at sign in.' : 'Add an authenticator code to protect your account.' }}</p>@if($user->two_factor_enabled)<form method="POST" action="{{ route('two-factor.disable') }}">@csrf @method('DELETE')<input name="password" type="password" placeholder="Current password" required><button class="button button-quiet" type="submit">Disable 2FA</button></form>@else<a class="button button-dark" href="{{ route('two-factor.setup') }}">Set up 2FA</a>@endif</section>
<section class="security-section"><h2>Active devices</h2>@foreach($devices as $device)<div class="device-row"><div><strong>{{ $device->name ?: 'Unknown device' }}</strong><span class="field-hint">{{ $device->ip_address }} · {{ optional($device->last_active_at)->diffForHumans() }}</span></div><form method="POST" action="{{ route('account.devices.revoke', $device) }}">@csrf @method('DELETE')<button class="button button-quiet" type="submit">{{ $device->session_id === $currentSessionId ? 'Sign out' : 'Revoke' }}</button></form></div>@endforeach<form method="POST" action="{{ route('account.devices.revoke-all') }}">@csrf<button class="button button-quiet" type="submit">Sign out all other devices</button></form></section>
<section class="security-section"><h2>Close account</h2><form method="POST" action="{{ route('account.deactivate') }}"><div class="field"><label for="deactivate_password">Password to deactivate</label><input id="deactivate_password" name="password" type="password" required></div>@csrf<button class="button button-quiet" type="submit">Deactivate account</button></form><form method="POST" action="{{ route('account.delete') }}">@csrf @method('DELETE')<input name="password" type="password" placeholder="Password to delete permanently" required><button class="button button-dark" type="submit">Delete account</button></form></section>
</div>
@endsection
